apiVersion: v1
kind: Service
metadata:
  name: gitops-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitops-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-app
  name: gitops-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - image: rodrigoreis90/spin-challenge:6.8.6
        imagePullPolicy: Always
        name: gitops-app
        ports:
        - containerPort: 8080
