apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app-deployment
  name: hello-app-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        imagePullPolicy: Always
        name: hello-app
        ports:
        - containerPort: 8080
