apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  labels:
    app: hello-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-app-deployment
  labels:
    app: spin-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spin-app
  template:
    metadata:
      labels:
        app: spin-app
    spec:
      containers:
      - name: spin-app
        image: rodrigoreis90/spin-challenge:2.0.1
        imagePullPolicy: Always

        ports:
        - containerPort: 5000